import "pkg:/source/utils/misc.bs"
sub init()
end sub

sub itemContentChanged()
  itemData = m.top.itemContent
  if not isValid(itemData) then return

  profileImage = m.top.findNode("profileImage")
  profileName = m.top.findNode("profileName")

  if itemData.imageURL = ""
    profileImage.uri = "pkg://images/icons/baseline_person_white_48dp.png"
  else
    profileImage.uri = itemData.imageURL
  end if
  profileName.text = itemData.name
end sub
